---
# ERROR: CAN'T FIND ANY SUPERWORKS
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'mark twain'
  -
    query: 'mark twain'
    subauth: 'work'
  -
    query: 'mark twain'
    subauth: 'superwork'
  -
    query: 'mark twain'
    subauth: 'instance'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/a640f1c3-982f-3ee2-a516-df7e6307d8c8'
#  -
#    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/171591'
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Work/Instance/UWASHINGTONon1015264193'
