---
authority:
  service: ld4l_cache
  context: true
search:
  -
    query: 'mark twain'
  -
    query: 'golden notebook'
term:
  -
    identifier: 'http://share-vde.org/sharevde/rdfBibframe/Instance/CORNELL196192'
